# Generated by Django 4.2.16 on 2024-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apartment_number", models.CharField(max_length=10)),
                ("pet_name", models.CharField(max_length=50)),
                ("pet_breed", models.CharField(max_length=50)),
                ("walk_date", models.DateField()),
                ("walk_time", models.TimeField()),
            ],
        ),
    ]
